[FEATURE] Implement Search Functionality for Job Applications
FurkannOzbek/application-hub pull request #24
Opened 2024-11-13 21:14 UTC by Natata08

# [FEATURE] Implement Search Functionality for Job Applications

---

## Description

Added search functionality to filter job applications by company name and job title, improving user experience by allowing quick access to specific applications. The implementation includes real-time filtering with a debounced search and an empty state display for no results.

- Problem: Users needed a way to quickly find specific job applications
- Impact: Improved application accessibility and user efficiency in managing multiple job applications

---

## Changes Made

Frontend:
1. Search Implementation:
- Added debounced search using `use-debounce` library
- Implemented filtering logic for company names and job titles
- Case-insensitive search with whitespace handling
2. Components:
- Modified SearchField component to handle search input
- Added EmptyState component for both no applications and no search results
- Updated ApplicationsBoard to handle filtered results
3. State Management:
- Added search state in DashboardPage
- Implemented filtered applications logic

---

## Screenshots (if applicable)
![screencapture-localhost-3000-user-2024-11-13-21_53_43](https://github.com/user-attachments/assets/92a8b837-1635-4376-b9a9-b803ed4591f6)

![screencapture-localhost-3000-user-2024-11-13-21_52_57](https://github.com/user-attachments/assets/635eab40-f673-41cb-88cb-86163113c7f7)

![screencapture-localhost-3000-user-2024-11-13-21_52_36](https://github.com/user-attachments/assets/0a4faec9-f73b-48e5-8c12-f0eacdf31b7c)

---

## Testing Steps

1. Search Functionality:
- Enter a company name in the search field
- Enter a job title in the search field
- Enter partial text to verify partial matches
- Clear search field to verify all applications return
2. Empty States:
- Search for non-existent company/title to verify empty state
- Verify empty state message changes based on search context
3. Edge Cases:
- Test with empty string
- Test with whitespace only
- Test with mixed case

---

## Issues Addressed

Closes [Add search functionality](https://trello.com/c/TcwaJYBo)

2024-11-13 23:28 UTC, olhasashchuk submitted a review, later dismissed

2024-11-14 08:18 UTC, pankaj28843 requested changes

2024-11-14 08:18 UTC, pankaj28843 commented on frontend/app/user/page.js
> +import { useDebounce } from 'use-debounce'
I would suggest using this library instead: https://github.com/streamich/react-use

It has `useDebounce` but also many other things, you won't need to add a new package for every new reusable hook you want.

2024-11-14 11:11 UTC, pankaj28843 approved these changes

2024-11-14 13:00 UTC, FurkannOzbek approved these changes

2024-11-14 13:03 UTC, merged