[FEATURE] Implement Sort Functionality for Job Applications
FurkannOzbek/application-hub pull request #31
Opened 2024-11-14 14:28 UTC by Natata08

# [FEATURE] Implement Sort Functionality for Job Applications

---

## Description

Added flexible sorting capabilities to the job applications dashboard, enabling users to organize their applications by different criteria.

Problem: Users needed to organise applications by different criteria
Impact: Enhanced organisation of job applications

---

## Changes Made

Frontend:
- DashboardPage: Added sort state management, and function of applying sorting after searching
- ApplicationsBoard: Updated to handle sorted applications
- Added utility function `sortApplications` 

---

## Screenshots (if applicable)

![screencapture-localhost-3000-user-2024-11-14-15_25_56](https://github.com/user-attachments/assets/26779bf7-c42c-4afa-9884-133aebce3f94)

![screencapture-localhost-3000-user-2024-11-14-15_18_06](https://github.com/user-attachments/assets/c131ea08-c11a-4933-8362-394708744a91)

---

## Testing Steps

1. Sort Functionality:
- Click sort dropdown and select different criteria:
- Test ascending/descending for each criteria
- Verify sort persistence between tab changes

2024-11-14 15:29 UTC, pankaj28843 requested changes

2024-11-14 15:29 UTC, pankaj28843 commented on frontend/utils/sortApplications.js
> +  'Created Date': (a, b) => compareDates(a.created_at, b.created_at),
Are these strings hardcoded in multiple places, making these constants and using them in components will be better IMHO.

2024-11-14 15:29 UTC, pankaj28843 commented on frontend/utils/sortApplications.js
> +  const multiplier = direction === 'asc' ? 1 : -1
same about declaring constants for `asc` `desc` as well, and use constants instead of hard-coded strings,

2024-11-14 17:32 UTC, Natata08 commented on frontend/utils/sortApplications.js
> +  const multiplier = direction === 'asc' ? 1 : -1
Fix it!

2024-11-14 17:37 UTC, pankaj28843 approved these changes

2024-11-15 00:07 UTC, FurkannOzbek approved these changes

2024-11-15 06:56 UTC, pankaj28843 approved these changes

2024-11-15 10:05 UTC, myselfankitaa approved these changes

2024-11-15 12:05 UTC, merged