[DB] Add database schema
FurkannOzbek/application-hub pull request #32
Opened 2024-11-14 18:54 UTC by Natata08

# [DB] Add database schema

---

## Description

This PR adds the initial database schema for the application's PostgreSQL database. The schema defines the core tables and relationships needed for managing job applications, companies, user data, and related entities.

---

## Changes Made

Added `api/db/schema.sql` file with the following key components:
- Core Tables:
   - user - User account information
   - company - Company details
   - application - Job application tracking
   - company_contact - Company contact information
   - application_note - Notes for applications
   - document - Document management
   - interview - Interview scheduling
   - notification - User notifications

- Additional Features:
   - Custom ENUM types for application status and document types
   - Automatic timestamp updates via triggers
   - Appropriate foreign key constraints
   - Indexes for performance optimization
   - Computed column for active applications

2024-11-14 19:11 UTC, pankaj28843 approved these changes

2024-11-14 19:49 UTC, olhasashchuk commented on api/db/schema.sql
> +    ROLE VARCHAR(100),
Why ROLE - uppercase?

2024-11-14 19:52 UTC, olhasashchuk commented on api/db/schema.sql
> +    CONTENT TEXT NOT NULL,
Also here Upper case

2024-11-14 19:58 UTC, pankaj28843 requested changes

2024-11-14 19:58 UTC, pankaj28843 commented on api/db/schema.sql
> +CREATE TABLE "company" (
add readme for using this sql script and make other changes like discussed on Slack

2024-11-14 19:59 UTC, Natata08 commented on api/db/schema.sql
> +    ROLE VARCHAR(100),
Prettier makes it uppercase, but it doesn't influence on table column.

2024-11-15 17:45 UTC, pankaj28843 submitted a review, later dismissed

2024-11-15 18:11 UTC, olhasashchuk approved these changes

2024-11-18 15:14 UTC, pankaj28843 approved these changes

2024-11-19 01:00 UTC, myselfankitaa approved these changes

2024-11-19 08:02 UTC, merged