Olha/UI/update/application page
FurkannOzbek/application-hub pull request #45
Opened 2024-11-18 00:41 UTC by olhasashchuk

# Pull Request Title:  
**Enhance Application Page [and](url) Responsiveness**

## Description of Changes:

This pull request includes several updates to improve the application management functionality, ensure better responsiveness across different devices, and streamline the application details display process. Additionally, it introduces mobile responsiveness, error handling, and better user experience on different devices. The following changes have been implemented:

### Application Component Updates:
1. **Integrated Error and Loading States**:
   - Improved user experience by handling loading and error states, ensuring the application only displays details (header, status, management panels) when the data has been successfully fetched.
   
2. **Components Display**:
   - The components (header, status, job details, etc.) are displayed only when the application data is available, improving performance and user experience.

### Mobile Responsiveness:
1. **Responsive Design Implementation**:
   - Introduced the `useIsMobile` hook to detect the device type (mobile or desktop).
   - Wrapped key components in a `ResponsiveWrapper` to adjust their layout based on screen size, ensuring the app works well across mobile and desktop devices.

### Date Picker Integration:
1. **DatePickerField Component**:
   - Added a custom `DatePickerField` to handle date fields with built-in validation.
   
2. **Updated AddApplicationForm**:
   - Integrated the `DatePickerField` component into the `AddApplicationForm` for selecting application and deadline dates, with full validation handling via `react-hook-form`.

### Localization Support:
1. **English Locale for Date Pickers**:
   - Configured date pickers to use the English locale (`enGB`) to improve internationalization and make the app suitable for different locales.

### Form Validation:
1. **Utilized `react-hook-form`**:
   - Improved form validation by integrating `react-hook-form` to manage form control, validation, and error handling, ensuring data is properly validated before submission.

### Manage Panel Structure:
1. **Components Added**:
   - **`ApplicationHeader`**: Displays the job title, company name, and location with a button to add a salary if missing.
   - **`ControlButton`**: A component for managing the application with buttons for editing, deleting, and navigating.
   - **`JobInfo`**: Displays job details such as job description, application date, and deadline date.
   - **`Contacts`**: A section for managing application contacts, with a card layout for each contact.
   - **`ManagePanel`**: The main panel structure that includes tabs for managing the application:
     - **Job**: Displays job-related information.
     - **Interview**: Placeholder for interview status and notes.
     - **Documents**: Placeholder for important documents.
     - **Notes**: Placeholder for application notes.
     - **Contacts**: Displays contact information.

## Related Issues:
- No related issues.

## How to Test:
1. Verify that the application displays correctly on both desktop and mobile devices, adjusting layout based on screen size.
2. Test that the application data only displays once the data is successfully fetched.
3. Ensure that the `DatePickerField` works correctly for selecting dates, and that form validation is functional.
4. Confirm that error and loading states are correctly handled during data fetching.
5. Check that all components (Job Info, Contacts, Notes, etc.) are displayed correctly.

## Screenshots:
- 
![Screenshot_4](https://github.com/user-attachments/assets/167c66f1-aca7-4f62-8eda-cc372f999a72)
![Screenshot_3](https://github.com/user-attachments/assets/e38c7234-4fab-4f10-9436-e61e5c6a90a2)
![Screenshot_2](https://github.com/user-attachments/assets/19162725-a752-4d39-8dfe-c9fb6cef3f37)
![Screenshot_1](https://github.com/user-attachments/assets/a6e7d843-26fd-429f-9be2-23f1747e2174)
![Screenshot_5](https://github.com/user-attachments/assets/10bc9656-0816-4390-9b4f-e0c08efcc528)

## Notes:
- This pull request focuses on the structure, design, and responsiveness of the application management system. Functionality and data handling will be implemented in future pull requests.

2024-11-18 14:46 UTC, Natata08 requested changes
Perfect job! I left just minor comments

2024-11-18 14:46 UTC, Natata08 commented on frontend/app/applications/[id]/ApplicationHeader.js
> +        component="div"
What do you think about making this component "h2" for semantics?

2024-11-18 14:46 UTC, Natata08 commented on frontend/app/applications/[id]/ApplicationHeader.js
> +import ManagePanel from './ManagePanel'
Could you please delete unused components: ControlButton, StatusPanel, ManagePanel

2024-11-18 14:46 UTC, Natata08 commented on frontend/app/applications/[id]/ApplicationHeader.js
> +              'Unpaid'
Cool!

2024-11-18 14:46 UTC, Natata08 commented on frontend/app/applications/[id]/ApplicationHeader.js
> +          component="div"
Maybe a paragraph would be better?

2024-11-18 14:46 UTC, Natata08 commented on frontend/app/applications/[id]/Contacts.js
> +              component="div"
Maybe component is also h5

2024-11-18 14:46 UTC, Natata08 commented on frontend/app/applications/[id]/ControlButton.js
> +    <>
Unnecessary fragments

2024-11-18 15:31 UTC, olhasashchuk commented on frontend/app/applications/[id]/StatusPanel.js
> +  const statuses = [
I will fix it in the future PR. And I want to use fetchStatuses.

2024-11-18 21:01 UTC, Natata08 approved these changes

2024-11-19 08:20 UTC, myselfankitaa approved these changes

2024-11-19 12:10 UTC, merged