[FEATURE] Implement Text Editor for Application Notes
FurkannOzbek/application-hub pull request #55
Opened 2024-11-21 20:00 UTC by Natata08

# [FEATURE] Implement Text Editor for Application Notes

---

## Description

This PR implements a rich text editor component for managing application notes using React-Quill. The component provides a user-friendly interface for creating, editing, and viewing notes associated with job applications.

Problem: Need a way to maintain detailed notes for each job application with rich text formatting
Impact: Users can now create and maintain formatted notes with features like headers, lists, and text styling

---

## Changes Made

### Frontend:
Notes Component:
- Implemented rich text editor using React-Quill
- Added edit/read modes with proper state management
- Implemented empty state display

Editor Styling:
- Added comprehensive theme-aware styling for the editor
- Implemented hover states and active states for toolbar buttons
- Ensured consistent styling with the application's theme

Empty State Component:
- Created separate component for empty state display
- Consistent styling with other empty states in the application

---

## Screenshots (if applicable)

### Empty state

![screencapture-localhost-3000-applications-39-2024-11-21-20_46_00](https://github.com/user-attachments/assets/03ed737b-01a4-400b-b01b-9f9877b9fe23)

![screencapture-localhost-3000-applications-39-2024-11-21-20_45_41](https://github.com/user-attachments/assets/0a253f49-e78a-4e17-815e-79e9fa4c8fe7)

### Editor in read mode
![screencapture-localhost-3000-applications-39-2024-11-21-20_53_08](https://github.com/user-attachments/assets/858f608b-553a-4779-8da1-a191357a6c4f)

![screencapture-localhost-3000-applications-39-2024-11-21-20_52_58](https://github.com/user-attachments/assets/e70d21fd-b73e-4d46-b729-326b582f977c)

### Editor in edit mode with toolbar
![screencapture-localhost-3000-applications-39-2024-11-21-20_52_30](https://github.com/user-attachments/assets/712fe587-7342-40dd-ac66-80d61310809c)

![screencapture-localhost-3000-applications-39-2024-11-21-20_52_47](https://github.com/user-attachments/assets/18ed4513-fd16-4488-845d-6d4818214716)

### On mobile:
![52D28205-7A7B-4380-92D2-9D72E557F8EA](https://github.com/user-attachments/assets/3ffbce5c-bf55-4b12-8903-7a7a59e3e426)

![A585D35D-01A2-4A33-9D07-A795BFC8788B](https://github.com/user-attachments/assets/86173a14-a428-4dcf-8dc0-ee4b646a3084)

![A585D35D-01A2-4A33-9D07-A795BFC8788B](https://github.com/user-attachments/assets/d3cc1d26-1599-4324-b24d-98cfec87b176)

---

## Testing Steps

1. Navigate to any application's details page
2. Click on the Notes tab
3. Verify empty state is displayed correctly
4. Test editor functionality:
 - Click Edit button
 - Try different text formatting options
 - Save changes
 - Cancel changes
5. Test responsive behavior on different screen sizes
6. Verify theme consistency in both light and dark modes
---

## Issues Addressed

Closes [Trello ticket link for Notes feature](https://trello.com/c/CNimWft4)

---

## Additional Notes

The next step is creating endpoints to get, put, and update notes from the Database.

2024-11-21 20:22 UTC, pankaj28843 requested changes
I suggest doing some profiling on this, and let's merge only after that.

2024-11-21 20:22 UTC, pankaj28843 commented on frontend/app/applications/[id]/notes/Notes.js
> +      quill.on('text-change', () => {
Shouldn't you extract this event handler as a function and in useEffect's return register `quill.off` for this event and the same function??

2024-11-21 20:22 UTC, pankaj28843 commented on frontend/app/applications/[id]/notes/Notes.js
> +  const editorStyles = {
See if useMemo on this gives better performance, now that you know how to do performance optimization for React components, it is a good idea to do profiling of such new components that rely on external JS libraries for rich features like text WYSIWYG editors.

2024-11-21 20:22 UTC, pankaj28843 commented on frontend/app/applications/[id]/notes/Notes.js
> +  const handleSave = async () => {
wrap it with `useCallback`

2024-11-21 20:22 UTC, pankaj28843 commented on frontend/app/applications/[id]/notes/Notes.js
> +  const handleCancel = () => {
Same thing about `useCallback`. Optimize for re-render, as much as possible.

2024-11-22 12:42 UTC, magdazelena reviewed
I agree with @pankaj28843 comments, added a small thing of my own.

Great job though!

2024-11-23 12:56 UTC, Natata08 commented on frontend/app/applications/[id]/notes/Notes.js
> +            </Button>
I hope I fixed it correctly

2024-11-23 18:19 UTC, pankaj28843 submitted a review, later dismissed
Looks good! 💯 💪🏻

2024-11-23 18:19 UTC, pankaj28843 commented on frontend/app/applications/[id]/notes/Notes.js
> +      console.log('notes:', value)
Did you forget to clean up this?

2024-11-24 07:54 UTC, myselfankitaa submitted a review, later dismissed

2024-11-24 09:02 UTC, pankaj28843 approved these changes

2024-11-24 12:03 UTC, myselfankitaa approved these changes

2024-11-24 12:04 UTC, merged