feat: Created HomePage with component, NavBar, Footer, Testimonials and an introduction
FurkannOzbek/application-hub pull request #6
Opened 2024-11-08 12:51 UTC by pankaj28843

# Pull Request Title

**Example:** [FEATURE] Implement User Authentication

---

## Description

Provide a brief summary of what this PR does. Include context, objectives, and any other relevant information.

- What problem does this PR solve?
- What is the impact of the change?

---

## Changes Made

List the main changes in this pull request. Describe what was added, modified, or removed.

- **Frontend:** Describe changes in the React components, hooks, or UI updates.
- **Backend:** Outline updates to Express.js routes, controllers, middleware, or database interactions.

---

## Screenshots (if applicable)

Add screenshots, GIFs, or videos that demonstrate the functionality or UI changes.

---

## Testing Steps

Describe how to test this feature or bug fix.

1. **Frontend:** List any specific UI interactions to test.
2. **Backend:** Outline API endpoints to test, expected responses, or integration points.

---

## Issues Addressed

Link any Tello issues that this pull request closes (if any).

**Example:** Closes (link to Trello ticket)

---

## Additional Notes

Share any other information, such as known issues, limitations, or follow-up tasks.

2024-11-08 15:53 UTC, pankaj28843 commented on frontend/app/layout.js
> +import NavBar from "@/components/navBar";
Please use consistent filenames, `navBar` and `Footer` have different casing.

2024-11-08 15:54 UTC, pankaj28843 commented on frontend/components/Footer.jsx
> +        backgroundColor: "#264240",
If you'are using MUI, please declare all color codes in the theme and use that name for the color instead of hard-coding them.

2024-11-08 15:56 UTC, pankaj28843 commented on frontend/components/Footer.jsx
> +              // src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMQEBAQExMWFg8WGBYQFxEXFRAVFRUVFRIXFxcXFhMYHSgiGB0lGxUTIjEhJSorLi4uFx8zODMtNygtLisBCgoKDg0OGxAQGi0lICUuLS0tKy0tLS0tLS
I would suggest extracting these dataurls into a `.jpeg` file and import that instead. Also, a transparent `.png` would be better, remove the whitespace around the logo, current header thickness is more than it needs to be.

2024-11-08 15:56 UTC, pankaj28843 commented on frontend/components/Footer.jsx
> +            NZ: +64 9 888 8606
Please remove fake details like phone numbers.

2024-11-08 15:58 UTC, pankaj28843 commented on frontend/components/HomePage.jsx
> +          backgroundColor: "#D2E8D4",
same comment about hard-coded color codes, please use named colors, define them in the theme.

2024-11-08 15:59 UTC, pankaj28843 commented on frontend/components/NavBar.jsx
> +            src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMQEBAQExMWFg8WGBYQFxEXFRAVFRUVFRIXFxcXFhMYHSgiGB0lGxUTIjEhJSorLi4uFx8zODMtNygtLisBCgoKDg0OGxAQGi0lICUuLS0tKy0tLS0tLS0tLS0
Same comment about having images as `.jpeg`/`.png` files

2024-11-09 09:46 UTC, myselfankitaa commented on frontend/app/layout.js
> +import NavBar from "@/components/navBar";
Ok noted, i have made the changes

2024-11-09 10:40 UTC, myselfankitaa commented on frontend/components/Footer.jsx
> +        backgroundColor: "#264240",
ok Noted

2024-11-09 10:41 UTC, myselfankitaa commented on frontend/components/HomePage.jsx
> +          backgroundColor: "#D2E8D4",
ok

2024-11-09 17:39 UTC, Natata08 requested changes
Ankita, good job! I hope, my comments are correct and useful. I'd suggest delete all imports of react and useTheme, and don't use `style` with MUI components. 
And I see a horizontal scroll but didn't find a reason for that.

2024-11-09 17:39 UTC, Natata08 commented on frontend/components/HomePage.jsx
> +import { useTheme } from "@mui/material/styles";
I think, you also don't need `useTheme` in your component, just write something like "background.paper".

2024-11-09 17:39 UTC, Natata08 commented on frontend/components/HomePage.jsx
> +export default function HomePage() {
You can be without a separate HomePage component by putting all these codes in the page.js.

2024-11-09 17:39 UTC, Natata08 commented on frontend/components/HomePage.jsx
> +          backgroundColor: theme.palette.background.cardLightGreen,
There is no such colour in the Theme.

2024-11-09 17:39 UTC, Natata08 commented on frontend/components/NavBar.jsx
> +          <img
What do you think about using Next.js Image component like:
'`<Image src="/transparentLogo.png" alt="logo of Application Hub" width={200} height={150} />`' and make it smaller.

2024-11-09 17:39 UTC, Natata08 commented on frontend/components/Footer.jsx
> +"use client";
This component doesn't need "use client" since it doesn't have client-side interactivity. And react import below.

2024-11-09 17:39 UTC, Natata08 commented on frontend/components/Introduction.jsx
> +        backgroundColor: theme.palette.background.default,
The same comments about this, just `bgcolor: 'background.default',` and we don't need Theme.

2024-11-09 17:39 UTC, Natata08 commented on frontend/components/Introduction.jsx
> +            backgroundColor: theme.palette.background.paperGreen,
This color and cardGreen aren't defined in out theme.

2024-11-09 17:39 UTC, Natata08 commented on frontend/components/Introduction.jsx
> +        <Button
I'd suggest using Next.js Link component for better client-side navigation.

2024-11-09 17:39 UTC, Natata08 commented on frontend/components/NavBar.jsx
> +          <Link href="/" passHref>
I'd suggest creating navItems to follow the DRY concept. 
```
const navItems = [
  { label: 'Home', path: '/' },
  { label: 'About', path: '/about' },
  { label: 'Dashboard', path: '/dashboard' },
];
```

2024-11-09 17:39 UTC, Natata08 commented on frontend/components/Overview.jsx
> +          component="p"
component="h2" for  better semantic HTML

2024-11-09 17:39 UTC, Natata08 commented on frontend/components/Overview.jsx
> +          color={theme.palette.background.paperGreen}
The same comments about colours.

2024-11-09 17:39 UTC, Natata08 commented on frontend/components/Testimonial.jsx
> +export default function TestimonialComponent() {
I'd suggest creating separated TestimonialCard for better maintainability.

2024-11-09 17:39 UTC, Natata08 commented on frontend/components/Testimonial.jsx
> +        style={{ alignItems: "center" }}
Maybe it wold be good idea to use `sx` for MUI components instead of `style`

2024-11-09 17:39 UTC, Natata08 commented on frontend/package.json
> +    "next": "^15.0.2",
Maybe it is better to use Next 14.

2024-11-10 12:02 UTC, olhasashchuk approved these changes

2024-11-10 12:02 UTC, Natata08 approved these changes

2024-11-10 12:03 UTC, merged