[REFACTOR] Improve API Request Handling and Error Management
FurkannOzbek/application-hub pull request #68
Opened 2024-11-25 19:08 UTC by Natata08

# [REFACTOR] Improve API Request Handling and Error Management

---

## Description

This PR implements a more robust and consistent approach to API request handling and error management across the application.
- Centralizes API request logic with a new apiRequest utility function
- Improves error handling with standardized error states
- Simplifies the motivational quote component with better state management

---

## Changes Made

### Frontend
- API Utilities (frontend/utils/api.js):
   - Implement a utility function to construct absolute URLs dynamically based on the environment's base URL 
   - Implement a new apiRequest utility function for centralized request handling
   - Standardized error handling across all API endpoints
   - Simplified API endpoint implementations using the new utility

- Motivational Quote Component (frontend/app/user/MotivationalQuote.js):
   - Refactored state management for better error handling

---

## Testing Steps

Test all CRUD operations for applications.

---

## Additional Notes

I am not sure about the current implementation of error handling because backend responses are not consistently structured across different endpoints.

2024-11-25 20:10 UTC, pankaj28843 requested changes

2024-11-25 20:10 UTC, pankaj28843 commented on frontend/utils/api.js
> +  if (relativeUrl.startsWith('http')) {
You should check for starting with `http://` or `https://` instead:

```js
const relativeUrl = "your-url-here";

if (/^https?:\/\//i.test(relativeUrl)) {
    console.log("URL starts with http:// or https://");
} else {
    console.log("URL does not start with http:// or https://");
}
```

2024-11-25 20:10 UTC, pankaj28843 commented on frontend/app/user/MotivationalQuote.js
> +              {!isLoading && !isError && <QuoteDisplay quote={quote} />}
Currently, these are 3 independent if statements. You can simplify this by writing a function:
```js
const renderContent = () => {
  if (isLoading) {
    return <Loading />;
  }
  if (isError) {
    return <ErrorMessage />;
  }
  return <QuoteDisplay quote={quote} />;
};

return <>{renderContent()}</>;
```

Or by using a ternary operator:
```
<>
  {isLoading ? (
    <Loading />
  ) : isError ? (
    <ErrorMessage />
  ) : (
    <QuoteDisplay quote={quote} />
  )}
</>
```

2024-11-25 20:10 UTC, pankaj28843 commented on frontend/utils/api.js
> +  relativeUrl,
rename this to `url`, as you optionally convert to an absolute URL.

2024-11-25 20:10 UTC, pankaj28843 commented on frontend/utils/api.js
> +    relativeUrl: 'https://api.api-ninjas.com/v1/quotes?category=success',
e.g. here `relativeUrl` feels wrong, if you rename the key to `url` it would look more coherent.

2024-11-25 20:10 UTC, pankaj28843 commented on frontend/utils/api.js
> +export const fetchQuote = async () => {
if there is no await you don't need async, clean it up everywhere.

Also, why is this not an arrow function without a body like the rest of them below this?

2024-11-26 10:11 UTC, Natata08 commented on frontend/utils/api.js
> +export const fetchQuote = async () => {
My fault, I forgot about this one

2024-11-26 10:51 UTC, olhasashchuk approved these changes

2024-11-26 11:08 UTC, merged