user endpoint fix (small update)
FurkannOzbek/application-hub pull request #7
Opened 2024-11-09 12:21 UTC by FurkannOzbek

## Description

- Unnecesarry functionality prevented. 
- Same functionality with less code

---

## Changes Made

- **Backend:**  As a result of our recent discussions, we removed unnecessary code to simplify the codebase. The api/user/:id endpoint has also been adjusted to api/user/me for a more intuitive experience.

---

## Testing Steps

**Backend:** If latest fetch has been done the route for /api/user/me can be tested by postman, requirements for testing the api :

Sending get request to the localhost:3001/api/user/me endpoint(if you running locally) with header; key : `Authorization` value : `Bearer <token> `

---

2024-11-09 16:10 UTC, pankaj28843 requested changes

2024-11-09 16:10 UTC, pankaj28843 commented on api/src/routers/user.js
> +  const requestedId = req.userInfo.userId;
I don't see much value in assigning this to a new variable here.

2024-11-09 21:07 UTC, FurkannOzbek commented on api/src/routers/user.js
> +  const requestedId = req.userInfo.userId;
Yes, its just a bad habit of mine to try put everything in variables for better visibility, but `req.userInfo.usedId` already clear enough itself, I ll fix right away :)

2024-11-09 21:57 UTC, olhasashchuk commented
You need to change code in Regester and Login routers in this part:
you code:
`return res.status(400).send("Username already exists");`
`res.status(201).send("registered succesfully");`
`res.status(500).send("Error registrariton: " + error.message);`

change to JSON format:
`return res.status(400).send.json({ message: "Email already in use" })`;
`res.status(201).send.json({ message:"registered succesfully"});`
`res.status(500).send.json({ message: "Error registrariton: " + error.message});`

Because in the client code, I expect the response to be in JSON format and try to call response.json(), which leads to the error.
![Screenshot_2](https://github.com/user-attachments/assets/16b35d6d-7744-4005-aa6d-80204adcfa39)

If I want to test for appearing error, for example username exists, I got error: "Unknown error" But I expect to see error with massege: 'Username already exists'.

2024-11-10 10:17 UTC, pankaj28843 approved these changes

2024-11-10 11:27 UTC, olhasashchuk approved these changes

2024-11-10 11:27 UTC, merged